language: node_js
node_js:
- 5.5.0
install:
- npm install
script:
- npm run lint && npm test && npm run build
sudo: false
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
deploy:
- provider: s3
  cache_control: private, no-store, no-cache, must-revalidate, max-age=0
  detect_encoding: true
  access_key_id: $AWS_KEY
  secret_access_key: $AWS_SECRET
  bucket: members-react.topcoder-dev.com
  skip_cleanup: true
  local_dir: dist
  on:
    branch: dev
- provider: s3
  cache_control: private, no-store, no-cache, must-revalidate, max-age=0
  detect_encoding: true
  access_key_id: $QA_AWS_KEY
  secret_access_key: $QA_AWS_SECRET
  bucket: members-react.topcoder-qa.com
  skip_cleanup: true
  local_dir: dist
  on:
    branch: qa
- provider: s3
  cache_control: private, no-store, no-cache, must-revalidate, max-age=0
  detect_encoding: true
  access_key_id: $MASTER_AWS_KEY
  secret_access_key: $MASTER_AWS_SECRET
  bucket: members-react.topcoder.com
  skip_cleanup: true
  local_dir: dist
  on:
    branch: master
env:
  matrix:
    - CXX=g++-4.8
  global:
    # DEV_AWS_KEY
    - secure: Q5GamehDjEF4sIdF85iLTYpg6lu0Y2JKvAF0rmmE+N3ixREESSlc6R6+C4M7oJEENKMvKvLTWKot/jPsE4qzxRUvlsh7zy8AMjaajhx+ztDPOT8yx0jUJeTH+Ez6KsAyLn/+CmM+d4Lp2JxOeC+feQ9BsdUwWuAAmyE24tcKdxzz4IeNKDtNeZFKgidcq9rog+A2t8QlMy13QXphCMJM2wvY+txUoQuWNTTVE/rDyP7iNBk0t6XsN/tp6xW01CISqeLQyZVbW1xNnWdkGVteGwECXxepZoRDTHhb8LattgnmO/zalIzFCIdiBR16xXqvv+eta+COInzZHRw8tQvo/NC3pjsgBX/qUQIKccs858rN5iOF0IXbxpQeuxoMeNqic9YqgGmXe9/ucZQ2ltQMpqevgkTtA+fTJ98rl8TN5MLjYGv8d2wSwmzPXFtaCgHXNGPTb2pCnyPiu0BoU9Z7D/i/L0pad4MQlXFcalz3hONm/weE7qe16wSf/2UQOtKMcto/MJRidzMcelxq6FPvA/aQZrpAq+jI3NiYdNiEvHXqfEaPD2dNMDzEAYhLEPpbV0uq+/suvTPEkABYpbYbY9/434LNvhPXwdxzUoPfWH3Y1gT0Nn2/5pp21dvtziv8Nejq8z43TJtou0qRQpeQtFaD/OEDNCROUfvdUomZbQU=
    # DEV_AWS_SECRET
    - secure: aujwdxDV3RflY+rZ16OfkRIBC/e4nkQzum/eOzIQYljctOkc3WeCBkqznT9eRb+g970PeQZzEd2skO/ZoyyhER3Cw8XGLUhb7ahR0jRFaW4NBBaePXYU4sH7VaieU3ypwV/EERbDtIxaEHsUU8Nw4971HajbrK00arca9dgNUec1h1qj36Aq9DhkHUoNhT6fapmiMD+1gPpefZWyPY0f/354RZFnyZoHng0IOLorgifBvqZKIJRpVQimsC7DUH5CrddtO7Us/ImCyqqyiPrWXuNTQmXjQ2LbF0QTxhVxpo7+ifKk/zRg6/b0DhUiyc0Xyt2aR7xZQMv7rIbHwqCjqWgMVV3zuN/3nYSLj6vCzU2y7JN01AMl3pZJnZfEkr43mJTPTtD1e3UE7U3vDYlH5BKTMV82HuOEneSdWJKZhuvXJo6xQNVrnpBc5rVFmZD9eejOLwlmOkFdJEYWNx4bJkVBgFGdeoE/7IFAzzKkYi9H8oQjW7h7ZCo+WgjvhpAdrRdhciPbzdNGLspToV8ttwql6u42eC/q8Tzi3ZrrVCyt8PBClGShMR93ezQoHXEsePHEgV6eKSRSrXDvR0Vdh7ZwoPiFHf6GOx7utlrCfkRKW977X0QkB3lHKlQfU9bcMatWeT8WeLRf7oWYEQx+x5/9a4lswvCr3lVUCxBsbZU=
    # # QA_AWS_KEY
    - secure: RVhGyu1c2f1jdXGEqgWQWgtANohP1oMtpWpesqkSAaDmQPtGjS4lbFLQeENDnp+FllQJALHmtCdBo7ireovcpSljPiTZA0iTRi0S1Ts/ka3L1DQE48O7pIVAGj9ssnNd51mYdmc8qtYagwWydNmTf8u8BKukjlxZSvBlZfFAiEjBfv8Ao13kPeTN39OGPq2aBxMPZEBtZze/RIXrwvtHac06tJX1hERcHqt7yD3NeldjtidhTEPyS0NvS9iUtr1xzB0s7Y0YwdfFeRnUlJgoLdnjG10jRWzdVrMUZkHUIOenxuoESbBc6qjk1XB0WUGm3W03cYZwkID7ZSKH/erWhSShtbRy28qG8aCLkn/HIOu6l/l86anmRuqEoqyHd/a+BoieBajeJph2810Oj5nNq49GPGF5jW7LC8p7Jt/H99T3JaR/iO2oN42e8Y5H7U9kpSMwNAEVdPdthBBgBLXCSSKmZbbHP54ij+uGrRIWl8rcadruN9A66W0KQVj+MdDlqrf0sm8n4BJaIEM5pacAWKtwxkNMcDYhAyTqOUSO6KA5EOpvES39kpPaXmjcKro/lxnJxHHKIup/ue52QFLtiB+hpGFlF2JXXgH4Yg0ZXlY5lQzc+NGQHvOmzIILvW/2/MjIQYEXL8DSXpu6h5MG1Jm5Vk5++rAEslLnl8F5gSQ=
    # # QA_AWS_SECRET
    - secure: p3DArz8QKsFy5wR4z+zy5NW32R1OQz/Zv6zeYhp7VRSvl+NxHkc4ZQBM/Ng+xL3gENphYxxoievJqwiYYbKQ3GJ6acuGFL3DMiCW293y49A6kGKH6KMO0NWHe5zNOEjAFZycq1g84GcQ9Hu3org863UYK+R12m8MtpeGnm56GShdHQMTPyKGnjJRVmS7WJI9uCfD+l/SeKtka7Fix7EXFOJN8qEGif6pvKa9NofmjGl8SxWtPbrCqYbvtF6qu475HmprXcVzSZiTAdDS+Y3+LmkCpVvPmZo/9MNg3G66M1jaUfxPawKhNWSHySRGdegQWJbBUu66DIduAHkMu9NFftF4CCduXnkl124EHQSaq/USxvA6vCv6ZPPIhjGNfguXdg5XtnkJHUpYUb9H/Ua1NJxrdRb5kGgp4EKI8BxiH9YSjbdOsC6ZTkgNwncyNoB5qT7LfYgN7aHXtMYwEPzwMYimFEE9fx5s+EPnsxkYrECjfQO07wNuV1S+nlqWoSwWtQwCesKfHeFtQDzX3q5pFI/0H3/SG60czTRPzl79ZeQW1kExlOuuTzi7ASO+MzudRW9M1JIXoVUBoaps4pdz0do0h9taookPtka1beyrgtPRPJ54Xb45Yswcnz9kGFwHAPA9ulVYAdOxHub7HoJ8L12gjg8Uc13yJicbE2OtbQI=
    # # MASTER_AWS_KEY
    - secure: N1Zs07/lBT7V9CXVtPk1N6larXbPwaBBM3LqfcCIVDIExhoAmdw48ZcuVLsgq0zO0BmDPQz7T3g57A+oed8iLvG8yt1gTnEhAzcTedsRNqDFMvXonQ0146BFfQUev5u/wzV+0ZJgGWlXHkYrKjK4bNUqt6aCktb4710hK0NTbdDhlxWkV0l0mXxmhWQWUE+4aPpDLoX3zpdaqOJ9DlfeIbEDg8J9cNlBZro+TlymTAEaD7V2GiOCitgnL5WfW0tWWkQz/2oDTpK1pSroo8y4T6HaLlGB+woa+YAE24hUXIPX/EFAVktZxIxevQWx90st5DopWlYmHj8OsbijhfV5uwxw8qbl/PThSGVapQGeKE/B/d7qSSEZokxILS4ha+an2vYkW5mCwCYdlqiKqBv1tp7glao121OFj+9TXhrs+c0Gm7oDMqKSpfczDWLuaaiQpFdITGI4rfFYjjokMlbS+wHmBSSeZC+dAMTxWomZzjjUSd+hZpuyB9p2jcZSnSchAscAeSwHYvN+TOS8DscJPtrbO0FiQEe28+CubNFIcZeFd76g8uf4umaSlpIbm93wb8KaVFUtvuWHCbMRho5MhehNWHyvDOZKMGGrQIUUWWmrbx8kBDUM3rGMdM/0OEYvrQVPpX4hbMQGBYjPAREFk0AuBTgKJi3emgdmmI7+e+U=
    # # MASTER_AWS_SECRET
    - secure: cbhRVLQZ+o0SH9+Htr0rJ7uaxqTxBdjdit1cZW2+Aq3FaFpvvg0g3wGRnUS9KmeOwGDqgwlbMO/0EfpKvzeQ/qf6U3GworIt5DOMLvimV1Aw7P4AU8tmm1Vc/RmN5n8y+lhtGE1/s8+xsxzUfSyH7Z6jTFr/Fa7i+UtgAzsUKYvrMUvk4xtto8d8GgF71mGQontUbIoU7jlh4Qt0pEFQEZofJPgEOP6fl+c5KwF/cgls2cIWuc1O8Gk96v7h0dpx/SacHYbx/b/iSQ+5yIEg5Qa5VEqnCESBWFOy0vB4kQv2HFPV4wFnB+xSs8ImZ/KmP55+6bZEV9E2DZCErlwUkOJu6rT1WUUSPaC/lWc6Cad1sjY4qBYQQPa5kZXMRq5YY9KeeIbhAbW8SViIvh9J6yFEgvjGeqjys67l9Pi+dQXbXrvn7VPexeTaQnxJdfmx//NwhyWqULRAkPJH0TdBKHzHSPtbJOlx95h283YH667ep6BsZzpNfnLIN4CDdWANx9+A+nBa91hDdMIwD1BOTmcUmbRms4/qq/2mZr7gA9jCEB0/El4wPZk6anJyC0f2FKP24otYozpfGqnD0jqjeCrfjT4cHbF2wamb/rjePUW3Lb845LnCuKqXz9OfTNkPd5kSq0sEkA5PPelE+Pq2QAVpnSTBLu5C2A72djgKuZc=
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8


# Notifications are not working
notifications:
  slack:
    secure: PMGlpdBoRzMlIjCsPWdXJ1wf550b+mpX0x44ggGWNL7ErpNebfyqIbXf4VJXYQDmhVJt31ygDaxTtj8XwZJlbvQjE6WGHU26KvL/efGJJL5EmgFD8LDBFpsbn49PyoZuVOTbSzqP8d8WCCPo4oBvX2r2Q2Ixh/tUx7i4Bcv0XwNpWAR75v1Yq/NftEI48k2GcI3oHqmuEgLHdP93k1rCUM4sBsgkr4PCltZfoE2AWlF6wY59w/oFiKj4FwycY8QjJZa/zbSQq1B/9QD7n4YBY4QjVv3LmjshEiQv1HGo2rNLV+/BB5ZoQ6JEH9h+seduHNTF+mkToKbJ2YjDERLlqLFYWVQKXTqFkSdYuknguJ3uOfXFaGtPDSqTRljE6WW6UDIJi9lDpxFHjH2q848/2O03RKtYeFKJWNbVb7Q2PWTBFxx6OurYra+tbUAorQiYmAQxd0vJY+qzGIDJZIQ8yDE4C10heOhfRyU8wJSKF3xJUKKWVGfBuHivFBZOETFSg0uVBcJnsXRcErvEQz0LuKaZfP81bIokcKUGxum/xyp9mYhYqWDvIj31RUhDMiRxXTPe9PhW0mlOtRG7tm2+8G08exHPSfONSV2IPUtlQt4j2/+I22ncOwtsm6yZzXXbDjoMR2sCHIyJj3lVECOqAnCfNJ6Q0CNJ93LqxKSHdFU=
