language: node_js
node_js:
- 5.5.0
install:
- npm install
script:
- npm run lint && npm run build
sudo: false
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
deploy:
- provider: s3
  cache_control: private, no-store, no-cache, must-revalidate, max-age=0
  detect_encoding: true
  access_key_id: $AWS_KEY
  secret_access_key: $AWS_SECRET
  bucket: members-react.topcoder-dev.com
  skip_cleanup: true
  local_dir: dist
  on:
    branch: dev
# - provider: s3
#   cache_control: private, no-store, no-cache, must-revalidate, max-age=0
#   detect_encoding: true
#   access_key_id: $QA_AWS_KEY
#   secret_access_key: $QA_AWS_SECRET
#   bucket: members-react.topcoder-qa.com
#   skip_cleanup: true
#   local_dir: dist
#   on:
#     branch: qa
# - provider: s3
#   cache_control: private, no-store, no-cache, must-revalidate, max-age=0
#   detect_encoding: true
#   access_key_id: $MASTER_AWS_KEY
#   secret_access_key: $MASTER_AWS_SECRET
#   bucket: members-react.topcoder.com
#   skip_cleanup: true
#   local_dir: dist
#   on:
#     branch: master
env:
  matrix:
    - CXX=g++-4.8
  global:
    # DEV_AWS_KEY
    - secure: Q5GamehDjEF4sIdF85iLTYpg6lu0Y2JKvAF0rmmE+N3ixREESSlc6R6+C4M7oJEENKMvKvLTWKot/jPsE4qzxRUvlsh7zy8AMjaajhx+ztDPOT8yx0jUJeTH+Ez6KsAyLn/+CmM+d4Lp2JxOeC+feQ9BsdUwWuAAmyE24tcKdxzz4IeNKDtNeZFKgidcq9rog+A2t8QlMy13QXphCMJM2wvY+txUoQuWNTTVE/rDyP7iNBk0t6XsN/tp6xW01CISqeLQyZVbW1xNnWdkGVteGwECXxepZoRDTHhb8LattgnmO/zalIzFCIdiBR16xXqvv+eta+COInzZHRw8tQvo/NC3pjsgBX/qUQIKccs858rN5iOF0IXbxpQeuxoMeNqic9YqgGmXe9/ucZQ2ltQMpqevgkTtA+fTJ98rl8TN5MLjYGv8d2wSwmzPXFtaCgHXNGPTb2pCnyPiu0BoU9Z7D/i/L0pad4MQlXFcalz3hONm/weE7qe16wSf/2UQOtKMcto/MJRidzMcelxq6FPvA/aQZrpAq+jI3NiYdNiEvHXqfEaPD2dNMDzEAYhLEPpbV0uq+/suvTPEkABYpbYbY9/434LNvhPXwdxzUoPfWH3Y1gT0Nn2/5pp21dvtziv8Nejq8z43TJtou0qRQpeQtFaD/OEDNCROUfvdUomZbQU=
    # DEV_AWS_SECRET
    - secure: aujwdxDV3RflY+rZ16OfkRIBC/e4nkQzum/eOzIQYljctOkc3WeCBkqznT9eRb+g970PeQZzEd2skO/ZoyyhER3Cw8XGLUhb7ahR0jRFaW4NBBaePXYU4sH7VaieU3ypwV/EERbDtIxaEHsUU8Nw4971HajbrK00arca9dgNUec1h1qj36Aq9DhkHUoNhT6fapmiMD+1gPpefZWyPY0f/354RZFnyZoHng0IOLorgifBvqZKIJRpVQimsC7DUH5CrddtO7Us/ImCyqqyiPrWXuNTQmXjQ2LbF0QTxhVxpo7+ifKk/zRg6/b0DhUiyc0Xyt2aR7xZQMv7rIbHwqCjqWgMVV3zuN/3nYSLj6vCzU2y7JN01AMl3pZJnZfEkr43mJTPTtD1e3UE7U3vDYlH5BKTMV82HuOEneSdWJKZhuvXJo6xQNVrnpBc5rVFmZD9eejOLwlmOkFdJEYWNx4bJkVBgFGdeoE/7IFAzzKkYi9H8oQjW7h7ZCo+WgjvhpAdrRdhciPbzdNGLspToV8ttwql6u42eC/q8Tzi3ZrrVCyt8PBClGShMR93ezQoHXEsePHEgV6eKSRSrXDvR0Vdh7ZwoPiFHf6GOx7utlrCfkRKW977X0QkB3lHKlQfU9bcMatWeT8WeLRf7oWYEQx+x5/9a4lswvCr3lVUCxBsbZU=
    # # QA_AWS_KEY
    # - secure: ADD ENCRYPTED QA KEY!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    # # QA_AWS_SECRET
    # - secure: ADD ENCRYPTED QA SECRET!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    # # MASTER_AWS_KEY
    # - secure: ADD ENCRYPTED PROD KEY!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    # # MASTER_AWS_SECRET
    # - secure: ADD ENCRYPTED PROD SECRET!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8


# Notifications are not working
notifications:
  slack:
    secure: PMGlpdBoRzMlIjCsPWdXJ1wf550b+mpX0x44ggGWNL7ErpNebfyqIbXf4VJXYQDmhVJt31ygDaxTtj8XwZJlbvQjE6WGHU26KvL/efGJJL5EmgFD8LDBFpsbn49PyoZuVOTbSzqP8d8WCCPo4oBvX2r2Q2Ixh/tUx7i4Bcv0XwNpWAR75v1Yq/NftEI48k2GcI3oHqmuEgLHdP93k1rCUM4sBsgkr4PCltZfoE2AWlF6wY59w/oFiKj4FwycY8QjJZa/zbSQq1B/9QD7n4YBY4QjVv3LmjshEiQv1HGo2rNLV+/BB5ZoQ6JEH9h+seduHNTF+mkToKbJ2YjDERLlqLFYWVQKXTqFkSdYuknguJ3uOfXFaGtPDSqTRljE6WW6UDIJi9lDpxFHjH2q848/2O03RKtYeFKJWNbVb7Q2PWTBFxx6OurYra+tbUAorQiYmAQxd0vJY+qzGIDJZIQ8yDE4C10heOhfRyU8wJSKF3xJUKKWVGfBuHivFBZOETFSg0uVBcJnsXRcErvEQz0LuKaZfP81bIokcKUGxum/xyp9mYhYqWDvIj31RUhDMiRxXTPe9PhW0mlOtRG7tm2+8G08exHPSfONSV2IPUtlQt4j2/+I22ncOwtsm6yZzXXbDjoMR2sCHIyJj3lVECOqAnCfNJ6Q0CNJ93LqxKSHdFU=
